import { Ticket } from '../../../types/ticket';

export const ticketData: Ticket[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'johndoe@mail.com',
    phone_number: '0123456789',
    position: 'Software Engineer',
    total_experience: '5 years',
    status: 'Pending',
    note: 'Needs follow-up on project requirements.',
    begin_date: new Date(),
    end_date: new Date(),
    proof_file: 'certificate-1.pdf'
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'janesmith@mail.com',
    phone_number: '0123456780',
    position: 'Product Manager',
    total_experience: '8 years',
    status: 'Verified',
    note: 'Completed product launch successfully.',
    begin_date: new Date(),
    proof_file: 'certificate-2.png'
  },
  {
    id: '3',
    name: 'Alice Johnson',
    email: 'alicejohnson@mail.com',
    phone_number: '0123456781',
    position: 'UX Designer',
    total_experience: '3 years',
    status: 'Pending',
    note: 'Working on wireframes for new app.',
    begin_date: new Date(),
    proof_file: 'certificate-3.jpg'
  },
  {
    id: '4',
    name: 'Bob Brown',
    email: 'bobbrown@mail.com',
    phone_number: '0123456782',
    position: 'DevOps Engineer',
    total_experience: '6 years',
    status: 'Rejected',
    note: 'Setting up CI/CD pipelines.',
    begin_date: new Date(),
    proof_file: 'certificate-4.pdf'
  },
  {
    id: '5',
    name: 'Charlie Green',
    email: 'charliegreen@mail.com',
    phone_number: '0123456783',
    position: 'QA Tester',
    total_experience: '4 years',
    status: 'Verified',
    note: 'Completed testing for version 2.0.',
    begin_date: new Date(),
    proof_file: 'certificate-5.pdf'
  },
  {
    id: '6',
    name: 'David Black',
    email: 'davidblack@mail.com',
    phone_number: '0123456784',
    position: 'Business Analyst',
    total_experience: '7 years',
    status: 'Verified',
    note: 'Analyzing market trends.',
    begin_date: new Date(),
    proof_file: 'certificate-6.pdf'
  },
  {
    id: '7',
    name: 'Emma White',
    email: 'emmawhite@mail.com',
    phone_number: '0123456785',
    position: 'Data Scientist',
    total_experience: '5 years',
    status: 'Pending',
    note: 'Developing predictive models.',
    begin_date: new Date(),
    proof_file: 'certificate-7.pdf'
  },
  {
    id: '8',
    name: 'Frank Moore',
    email: 'frankmoore@mail.com',
    phone_number: '0123456786',
    position: 'Project Manager',
    total_experience: '10 years',
    status: 'Verified',
    note: 'Managing large-scale projects.',
    begin_date: new Date(),
    proof_file: 'certificate-8.pdf'
  },
  {
    id: '9',
    name: 'Grace Lee',
    email: 'gracelee@mail.com',
    phone_number: '0123456787',
    position: 'HR Specialist',
    total_experience: '4 years',
    status: 'Pending',
    note: 'Overseeing recruitment process.',
    begin_date: new Date(),
    proof_file: 'certificate-9.pdf'
  },
  {
    id: '10',
    name: 'Henry Taylor',
    email: 'henrytaylor@mail.com',
    phone_number: '0123456788',
    position: 'Network Engineer',
    total_experience: '6 years',
    status: 'Rejected',
    note: 'Maintaining network infrastructure.',
    begin_date: new Date(),
    proof_file: 'certificate-10.pdf'
  },
  {
    id: '11',
    name: 'Isabella Clark',
    email: 'isabellaclark@mail.com',
    phone_number: '0123456789',
    position: 'Marketing Manager',
    total_experience: '9 years',
    status: 'Verified',
    note: 'Planning marketing campaigns.',
    begin_date: new Date(),
    proof_file: 'certificate-11.pdf'
  },
  {
    id: '12',
    name: 'Jack Wilson',
    email: 'jackwilson@mail.com',
    phone_number: '0123456790',
    position: 'Security Analyst',
    total_experience: '5 years',
    status: 'Pending',
    note: 'Monitoring security systems.',
    begin_date: new Date(),
    proof_file: 'certificate-12.pdf'
  },
  {
    id: '13',
    name: 'Karen Martinez',
    email: 'karenmartinez@mail.com',
    phone_number: '0123456791',
    position: 'Content Writer',
    total_experience: '3 years',
    status: 'Verified',
    note: 'Writing articles and blogs.',
    begin_date: new Date(),
    proof_file: 'certificate-13.pdf'
  },
  {
    id: '14',
    name: 'Leo Anderson',
    email: 'leoanderson@mail.com',
    phone_number: '0123456792',
    position: 'Full Stack Developer',
    total_experience: '8 years',
    status: 'Verified',
    note: 'Developing web applications.',
    begin_date: new Date(),
    proof_file: 'certificate-14.pdf'
  },
  {
    id: '15',
    name: 'Mia Thomas',
    email: 'miathomas@mail.com',
    phone_number: '0123456793',
    position: 'Database Administrator',
    total_experience: '6 years',
    status: 'Pending',
    note: 'Managing database systems.',
    begin_date: new Date(),
    proof_file: 'certificate-15.pdf'
  },
  {
    id: '16',
    name: 'Noah Harris',
    email: 'noahharris@mail.com',
    phone_number: '0123456794',
    position: 'Frontend Developer',
    total_experience: '4 years',
    status: 'Rejected',
    note: 'Creating user interfaces.',
    begin_date: new Date(),
    proof_file: 'certificate-16.pdf'
  },
  {
    id: '17',
    name: 'Olivia Robinson',
    email: 'oliviarobinson@mail.com',
    phone_number: '0123456795',
    position: 'Backend Developer',
    total_experience: '5 years',
    status: 'Verified',
    note: 'Developing server-side logic.',
    begin_date: new Date(),
    proof_file: 'certificate-17.pdf'
  },
  {
    id: '18',
    name: 'Paul King',
    email: 'paulking@mail.com',
    phone_number: '0123456796',
    position: 'System Administrator',
    total_experience: '7 years',
    status: 'Pending',
    note: 'Maintaining IT systems.',
    begin_date: new Date(),
    proof_file: 'certificate-18.pdf'
  },
  {
    id: '19',
    name: 'Quinn Scott',
    email: 'quinnscott@mail.com',
    phone_number: '0123456797',
    position: 'Technical Writer',
    total_experience: '5 years',
    status: 'Verified',
    note: 'Creating technical documentation.',
    begin_date: new Date(),
    proof_file: 'certificate-19.pdf'
  },
  {
    id: '20',
    name: 'Rachel Young',
    email: 'rachelyoung@mail.com',
    phone_number: '0123456798',
    position: 'Graphic Designer',
    total_experience: '4 years',
    status: 'Pending',
    note: 'Designing marketing materials.',
    begin_date: new Date(),
    proof_file: 'certificate-20.pdf'
  }
];
